--Criando as tabelas do projeto

--TABELA EMPRESA
CREATE TABLE EMPRESA
(
    COD_EMPRESA INT NOT NULL PRIMARY KEY,
    NOME_EMPRESA VARCHAR2(50),
    FANTASIA VARCHAR2(15)
);

--Criando uma sequencia para o codigo da empresa
CREATE SEQUENCE SEQ_EMP START WITH 1 INCREMENT BY 1 NOMAXVALUE;


--TABELA UF. QUE SERÁ UTILIZADA POR TODAS AS EMPRESAS
CREATE TABLE UF
(
    COD_UF VARCHAR2(2) NOT NULL PRIMARY KEY,
    SIGLA_UF VARCHAR2 (2) NOT NULL,
    NOME_UF VARCHAR2(30) NOT NULL
);


--TABELA CIDADE. SERÁ UTILIZADO POR TODAS AS EMPRESAS
CREATE TABLE CIDADES
(
    COD_CIDADE VARCHAR2(7) NOT NULL PRIMARY KEY,
    COD_UF VARCHAR2(2) NOT NULL,
    NOME_CIDADE VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_CID1 FOREIGN KEY (COD_UF) REFERENCES UF(COD_UF)
);


--TABELA CLIENTES
CREATE TABLE CLIENTES
(
    COD_EMPRESA INT NOT NULL,
	ID_CLIENTE INT NOT NULL PRIMARY KEY,
	RAZAO_CLIENTE VARCHAR2(100)NOT NULL,
	FANTASIA VARCHAR2(15) NOT NULL,
	ENDERECO VARCHAR2(50) NOT NULL,
	NRO VARCHAR2(10) NOT NULL,
	BAIRRO VARCHAR2(20) NOT NULL,
	COD_CIDADE VARCHAR2(7) NOT NULL,
	CEP VARCHAR2(8),
	CNPJ_CPF VARCHAR2(15),
	TIPO_CLIENTE CHAR(1) CONSTRAINT CK_TC1 CHECK (TIPO_CLIENTE in ('F', 'J')),
	DATA_CADASTRO DATE NOT NULL,
	COD_PAGTO INT ,
    CONSTRAINT FK_COD_EMP1 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA),
	CONSTRAINT FK_CLI1 FOREIGN KEY (COD_CIDADE) REFERENCES CIDADES(COD_CIDADE)
);

--CRIANDO A SEQUENCIA DO CLIENTE
CREATE SEQUENCE SEQ_CLI START WITH 1 INCREMENT BY 1 NOMAXVALUE;


--TABELA FORNECEDORES
CREATE TABLE FORNECEDORES
(  
    COD_EMPRESA INT NOT NULL,
    ID_FOR INT  NOT NULL PRIMARY KEY,
	RAZAO_FORNEC VARCHAR2(100)NOT NULL,
	FANTASIA VARCHAR2(15) NOT NULL,
	ENDERECO VARCHAR2(50) NOT NULL,
	NRO VARCHAR2(10) NOT NULL,
	BAIRRO VARCHAR2(20) NOT NULL,
	COD_CIDADE VARCHAR2(7) NOT NULL,
	CEP VARCHAR2(8),
	CNPJ_CPF VARCHAR2(15),
	TIPO_FORNEC CHAR(1) CONSTRAINT CK_TF1 CHECK (TIPO_FORNEC in ('F', 'J')),
	DATA_CADASTRO DATE NOT NULL,
	COD_PAGTO INT ,
    CONSTRAINT FK_COD_EMP2 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA),
	CONSTRAINT FK_FOR1 FOREIGN KEY (COD_CIDADE) REFERENCES CIDADES(COD_CIDADE)
);
    
 -- CRIANDO SEQUENCIA PARA FORNECEDORES;  
 CREATE SEQUENCE SEQ_FOR START WITH 1 INCREMENT BY 1 NOMAXVALUE;


--TABELA TIPO DE MATERIAL
CREATE TABLE TIPO_MAT
(
	COD_TIP_MAT INT  NOT NULL PRIMARY KEY,
	DESC_TIP_MAT VARCHAR2(20) NOT NULL
);

--CRIANDO SEQUENCIA TIPO MATERIAL
CREATE SEQUENCE SEQ_TIP_MAT START WITH 1 INCREMENT BY 1 NOMAXVALUE;


--TABELA MATERIAL
CREATE TABLE MATERIAL
(
    COD_EMPRESA INT NOT NULL,
	COD_MAT INT NOT NULL,
	DESCRICAO VARCHAR2(50) NOT NULL,
	PRECO_UNIT DECIMAL(10,2) NOT NULL,
	COD_TIP_MAT INT NOT NULL,
    CONSTRAINT FK_COD_EMP3 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA),
	CONSTRAINT FK_MAT1 FOREIGN KEY (COD_TIP_MAT) REFERENCES TIPO_MAT(COD_TIP_MAT),
    CONSTRAINT PK_EMP_MAT PRIMARY KEY (COD_EMPRESA,COD_MAT)
);

--TABELA DE RELACIONAMENTO ENTRE MATERIAL POR FORNECEDOR
CREATE TABLE MAT_FORNEC
(
    COD_EMPRESA INT NOT NULL,
    COD_MAT INT NOT NULL,
    ID_FOR INT NOT NULL,
    CONSTRAINT PK_MAT_FOR PRIMARY KEY (COD_EMPRESA,COD_MAT,ID_FOR),
    CONSTRAINT FK_MAT_FOR1 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA),
    CONSTRAINT FK_MAR_FOR2 FOREIGN KEY (ID_FOR) REFERENCES FORNECEDORES(ID_FOR)
);

--CRIANDO INDEX PARA OTIMIZAR AS OPERAÇÕES DE CONSULTA
--CREATE INDEX IX_MAT1 ON MATERIAL (COD_EMPRESA, COD_MAT);
CREATE INDEX IX_MAT2 ON MATERIAL (COD_TIP_MAT);


--TABELA ORDEM DE PRODUÇÃO
CREATE TABLE ORDEM_PROD
(
    COD_EMPRESA INT NOT NULL,
	ID_ORDEM INT NOT NULL PRIMARY KEY,
	COD_MAT_PROD INT NOT NULL,
	QTD_PLAN DECIMAL(10,2) NOT NULL,
	QTD_PROD DECIMAL(10,2) NOT NULL,
	DATA_INI DATE,
	DATA_FIM DATE,
	SITUACAO CHAR(1) CONSTRAINT CK_OP1 CHECK (SITUACAO in ('A','P','F')),--A-ABERTA, P-PLANEJADA -F-FECHADA
    CONSTRAINT FK_OP1 FOREIGN KEY (COD_MAT_PROD,COD_EMPRESA) REFERENCES MATERIAL(COD_MAT,COD_EMPRESA)
    --CONSTRAINT FK_COD_EMP4 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA)
);

--CRIANDO SEQUENCIA ORDEM DE PRODUCAO
 CREATE SEQUENCE SEQ_OP START WITH 1 INCREMENT BY 1 NOMAXVALUE;


--TABELA DE APONTAMENTOS
CREATE TABLE APONTAMENTOS
(
    COD_EMPRESA INT NOT NULL,
	ID_APON INT NOT NULL PRIMARY KEY,
	ID_ORDEM INT NOT NULL,
	COD_MAT_PROD INT,
	QTD_APON DECIMAL(10,2),
	DATA_APON DATE NOT NULL,
	--CAMPO LOTE CRIADO NO FINAL
	--LOGIN, SERA CRIADO APOIS CRIACAO DA TABELA USUARIOS
    CONSTRAINT FK_AP1 FOREIGN KEY (COD_MAT_PROD,COD_EMPRESA) REFERENCES MATERIAL(COD_MAT,COD_EMPRESA),
	CONSTRAINT FK_APON1 FOREIGN KEY (ID_ORDEM) REFERENCES ORDEM_PROD(ID_ORDEM)
);

-- CRIANDO SEQUENCIA PARA TABELA APONTAMENTOS
CREATE SEQUENCE SEQ_APON START WITH 1 INCREMENT BY 1 NOMAXVALUE;

--TABELA FICHA TÉCNICA
CREATE TABLE FICHA_TECNICA
(
    COD_EMPRESA INT NOT NULL,
	COD_MAT_PROD INT NOT NULL,
	COD_MAT_NECES INT NOT NULL,
	QTD_NECES DECIMAL(10,2) NOT NULL,
	CONSTRAINT FK_FIC1 FOREIGN KEY (COD_EMPRESA,COD_MAT_PROD) REFERENCES MATERIAL(COD_EMPRESA,COD_MAT),
	CONSTRAINT FK_FIC2 FOREIGN KEY (COD_EMPRESA,COD_MAT_NECES) REFERENCES MATERIAL(COD_EMPRESA,COD_MAT)
);

-- CRIANDO SEQUENCIA PARA TABELA FICHA_TECNICA
CREATE SEQUENCE SEQ_FT START WITH 1 INCREMENT BY 1 NOMAXVALUE;



--TABELA CONSUMO. RASTREABILIDADE DO QUE FOI USADO
CREATE TABLE CONSUMO
(
	ID_APON INT NOT NULL,
    COD_EMPRESA INT NOT NULL,
	COD_MAT_NECES INT NOT NULL,
	QTD_CONSUMIDA DECIMAL(10,2) NOT NULL,
	LOTE VARCHAR2(20) NOT NULL,
	CONSTRAINT FK_CONS1 FOREIGN KEY (COD_EMPRESA,COD_MAT_NECES) REFERENCES MATERIAL(COD_EMPRESA,COD_MAT),
	CONSTRAINT FK_CONS2 FOREIGN KEY (ID_APON)  REFERENCES APONTAMENTOS(ID_APON)
);


















