

create table FUNCIONARIO
(
    MATRICULA INT NOT NULL PRIMARY KEY,
    NOME       VARCHAR2(50) NOT NULL,
    SOBRENOME  VARCHAR2(50) NOT NULL, 
    ENDERECO   VARCHAR2(50),
    CIDADE     VARCHAR2(50),
    PAIS       VARCHAR2(25),
    DATA_NASC  DATE
)

CREATE SEQUENCE ID_FUNC2
    START WITH   1
    INCREMENT BY 1
    NOCACHE;

CREATE TABLE SALARIO 
(
    MATRICULA INT NOT NULL,
    SALARIO DECIMAL (10, 2) NOT NULL,
    FOREIGN KEY(MATRICULA) REFERENCES FUNCIONARIO(MATRICULA)
)


CREATE TABLE AUDIT_SALARIO
(
    TRANSACAO   INT NOT NULL, 
    MATRICULA   INT NOT NULL,
    DATA_TRANS  TIMESTAMP NOT NULL,
    SAL_ANTIGO  DECIMAL (10,2),
    SAL_NOVO  DECIMAL (10,2),
    USUARIO VARCHAR2(20) NOT NULL,
    PRIMARY KEY(TRANSACAO),
    FOREIGN KEY(MATRICULA) REFERENCES FUNCIONARIO(MATRICULA)
);

CREATE SEQUENCE ID_TRAN
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
    
-- Index, otimiza a execução de comandos DML
CREATE INDEX IX_FUNC1 ON FUNCIONARIO(DATA_NASC);

CREATE INDEX IX_FUNC2 ON FUNCIONARIO(CIDADE,PAIS);
       
 --Adicionando uma nova coluna   
ALTER TABLE FUNCIONARIO ADD GENERO CHAR(1);    

--Renomeando uma coluna  
ALTER TABLE FUNCIONARIO RENAME COLUMN GENERO TO SEXO;

--Alterando o tipo da coluna    
ALTER TABLE FUNCIONARIO MODIFY SEXO VARCHAR2(1);    
    
--Alterando o nome da Tabela
ALTER TABLE FUNCIONARIO
RENAME TO PESSOA;

--RETORNANDO
ALTER TABLE FUNCIONARIO
RENAME TO FUNCIONARIO;

--ALTERANDO O TIPO DE UMA COLUNA    
ALTER TABLE FUNCIONARIO MODIFY ENDERECO VARCHAR2(30); 

--EXCLUINDO UMA COLUNA
ALTER TABLE FUNCIONARIO DROP COLUMN SEXO;
    
    

--EXCLUINDO UMA TABLEA
DROP TABLE SALARIO

--DANDO PRIVILEGIOS AO ALUNO
GRANT DBA TO ALUNO  
GRANT ALL PRIVILEGES TO aluno

--CRIANDO UMA VIEW
CREATE VIEW  v_funcionario
    AS
    SELECT * FROM FUNCIONARIOS
    
SELECT * FROM V_FUNCIONARIO

--EDITANDO A VIEW
CREATE OR REPLACE VIEW v_funcionario
	AS 
	SELECT ID,NOME FROM FUNCIONARIOS;

--APAGANDO A VIEW
DROP VIEW v_funcionario
    
    

    
--DDL    
CREATE DATABASE Teste;
DROP DATABASE Teste; 
       

-- CRIANDO UMA TABELA TEMPORARIA
CREATE GLOBAL TEMPORARY TABLE TMP_FUNCIONARIOS
(
    ID INT,
    NOME VARCHAR2(50),
    SALARIO DECIMAL(10,2),
    SETOR VARCHAR2(30)
);

--FAZENDO BK NA TABELA TEMPORARIA
INSERT INTO TMP_FUNCIONARIOS
SELECT * FROM FUNCIONARIOS

--VERIFICANDO BK NA TABELA TAMPORÁRIA    
SELECT * FROM TMP_FUNCIONARIOS    
    
    
    
    
    
    
    
    