select * from senso;

--Min, Max, AVG, SUM, COUNT, STADDEV, VARIANCE;

--AVG
--Calculando a Média da população de 2014;
select AVG(POPULACAO) AS MEDIA FROM SENSO
WHERE ANO = '2014';

--Média da população por estado em 2014;
SELECT estado, AVG(POPULACAO) FROM SENSO
 WHERE ANO = '2014'
 GROUP BY ESTADO
 ORDER BY 2 DESC;
 
 --Média por estado com sigla do Estado;
 SELECT A.COD_uf, B.SIGLA_UF, AVG(POPULACAO) MEDIA
   FROM SENSO A 
  INNER JOIN UF B ON (A.COD_UF = B.COD_UF)
  WHERE A.ANO = '2014'
  GROUP BY A.COD_UF, B.SIGLA_UF
  ORDER BY 3 DESC;
  
--Média por região
SELECT A.REGIAO, AVG(A.POPULACAO)   
  FROM SENSO A
 WHERE A.ANO = '2014'
 GROUP BY A.REGIAO;
 
 
 
 --COUNT
 --Número de cidades por ano
SELECT A.ANO, COUNT(*) QTD_CIDADES FROM SENSO A
GROUP BY A.ANO;

--Quantidade de Estados;
SELECT COUNT(DISTINCT COD_UF) FROM SENSO;

--Quantidade de cidades por regiões'
SELECT A.REGIAO, COUNT (*) FROM SENSO A
WHERE ANO = '2014'
GROUP BY A.REGIAO
ORDER BY 2 DESC;

  

--STTDEV
--dESVIO PADRÃO ESTÍSTICO PARA A POPULAÇÃO DE TODOS OS VAALORES NA EXPRESSÃO EPECIFICA
SELECT STTDEV(A.POPULACAO) FROM SENSO A
WHERE ANO = '2014';
  
  
--VAR_POP
--VARIANCIA ESTATISTICA
SELECT VAR_POP(POPULACAO) FROM SENSO
WHERE ANO = '2014';
  
  
  
  
  
  
  
  